name: Postgres
on: [push, pull_request]

jobs:
  postgres:
    runs-on: ubuntu-20.04
    services:
      postgres:
        # 12 is chosen because that matches the version of the client utils we will install
        image: postgres:12
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432/tcp
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt-get -y install postgresql-client-12
    - run: psql -h localhost -U postgres --no-password -d postgres -c "CREATE TABLE foo ( id INTEGER PRIMARY KEY )"
      env:
        PGPASSWORD: postgres
    - run: pg_dump -h localhost -U postgres --no-password -f shouldbe.sql postgres
      env:
        PGPASSWORD: postgres
    - run: diff database/database.sql shouldbe.sql
