name: Postgres
on: [push, pull_request]

jobs:
  postgres:
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432/tcp
    steps:
    - uses: actions/checkout@v2
    - run: docker run -it --rm postgres:14 pg_dump --help
